/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type ExpenseCategory = typeof ExpenseCategory[keyof typeof ExpenseCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExpenseCategory = {
  SERVICE: 'SERVICE',
  PRODUCT: 'PRODUCT',
  PROVIDER: 'PROVIDER',
} as const;
