/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type ExpenseLogAction = typeof ExpenseLogAction[keyof typeof ExpenseLogAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExpenseLogAction = {
  EDIT_EXPENSE: 'EDIT_EXPENSE',
} as const;
