/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */
import type { UserRole } from './userRole';
import type { ExpenseLogAction } from './expenseLogAction';

export interface ExpenseLogDTO {
  id: string;
  createdAt: string;
  modifiedAt: string;
  author: string;
  field: string;
  oldValue?: string;
  newValue?: string;
  role: UserRole;
  action: ExpenseLogAction;
  expenseId: string;
}
