/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type GetExpenseLogsParams = { q?: string | null; page?: number; size?: number; date_from?: string; date_to?: string };
