/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type ReviewStatus = typeof ReviewStatus[keyof typeof ReviewStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REFUSED: 'REFUSED',
  INFO_REQUIRED: 'INFO_REQUIRED',
} as const;
