/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  REVIEWER: 'REVIEWER',
  EMPLOYEE: 'EMPLOYEE',
} as const;
