/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */
import type {
  ExpenseDTO,
  GetExpensesParams,
  CreateExpenseDTO,
  UpdateExpenseDTO,
  ExpenseLogDTO,
  GetExpenseLogsParams
} from '../../types'
import { customInstance } from '.././config'



  export const getExpenses = (
    params?: GetExpensesParams,
 ) => {
      return customInstance<ExpenseDTO[]>(
      {url: `/expenses`, method: 'get',
        params
    },
      );
    }
  export const createExpense = (
    createExpenseDTO: CreateExpenseDTO,
 ) => {
      return customInstance<ExpenseDTO>(
      {url: `/expenses`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: createExpenseDTO
    },
      );
    }
  export const getExpense = (
    expenseId: string,
 ) => {
      return customInstance<ExpenseDTO>(
      {url: `/expenses/${expenseId}`, method: 'get'
    },
      );
    }
  export const updateExpense = (
    expenseId: string,
    updateExpenseDTO: UpdateExpenseDTO,
 ) => {
      return customInstance<ExpenseDTO>(
      {url: `/expenses/${expenseId}`, method: 'put',
      headers: {'Content-Type': 'application/json', },
      data: updateExpenseDTO
    },
      );
    }
  export const getExpenseLogs = (
    expenseId: string,
    params?: GetExpenseLogsParams,
 ) => {
      return customInstance<ExpenseLogDTO[]>(
      {url: `/expenses/${expenseId}/logs`, method: 'get',
        params
    },
      );
    }
  