schema:
    enums:
        ExpenseCategory:
            - SERVICE
            - PRODUCT
            - PROVIDER
        ReviewStatus:
            - PENDING
            - APPROVED
            - REFUSED
            - INFO_REQUIRED
        RefundStatus:
            - PENDING
            - ACCEPTED
            - REFUSED
        UserRole:
            - ADMIN
            - OPERATOR
            - REVIEWER
            - EMPLOYEE
        ExpenseLogAction:
            - EDIT_EXPENSE
    models:
        Expense:
            properties:
                id:
                    type: id
                createdAt:
                    type: createdAt
                modifiedAt:
                    type: modifiedAt
                totalAmount:
                    type: int
                categorization:
                    type: enum
                    ref: ExpenseCategory
                    default: SERVICE
                programId:
                    type: uuid
                expenseAt:
                    type: datetime
                reviewStatus:
                    type: enum
                    ref: ReviewStatus
                    default: PENDING
                refundStatus:
                    type: enum
                    ref: RefundStatus
                    default: PENDING
                parentExpenseId:
                    type: foreignKey
                    ref: Expense
                    field: id
                    nullable: true
                    foreignKeyName: ParentExpense
        ExpenseLog:
            properties:
                id:
                    type: id
                createdAt:
                    type: createdAt
                modifiedAt:
                    type: modifiedAt
                author:
                    type: string
                field:
                    type: string
                oldValue:
                    type: string
                    nullable: true
                newValue:
                    type: string
                    nullable: true
                role:
                    type: enum
                    ref: UserRole
                    default: EMPLOYEE
                action:
                    type: enum
                    ref: ExpenseLogAction
                    default: EDIT_EXPENSE
                expenseId:
                    type: foreignKey
                    ref: Expense
                    field: id
                    foreignKeyName: Expense
