/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateExpense - 
func CreateExpense(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetExpense - 
func GetExpense(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetExpenseLogs - 
func GetExpenseLogs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetExpenses - 
func GetExpenses(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateExpense - 
func UpdateExpense(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
