/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ExpenseDto struct {

	Id string `json:"id"`

	// The creation date of the expense
	CreatedAt time.Time `json:"createdAt"`

	// The modification date of the expense
	ModifiedAt time.Time `json:"modifiedAt"`

	Categorization ExpenseCategory `json:"categorization"`

	// The ID of the allocated program
	ProgramId string `json:"programId"`

	// The date of the expense
	ExpenseAt time.Time `json:"expenseAt"`

	// The total amount
	TotalAmount float32 `json:"totalAmount"`

	ReviewStatus ReviewStatus `json:"reviewStatus"`

	RefundStatus RefundStatus `json:"refundStatus"`
}
