/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ExpenseCategory string

// List of ExpenseCategory
const (
	EXPENSECATEGORY_SERVICE ExpenseCategory = "SERVICE"
	EXPENSECATEGORY_PRODUCT ExpenseCategory = "PRODUCT"
	EXPENSECATEGORY_PROVIDER ExpenseCategory = "PROVIDER"
)
