/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type RefundStatus string

// List of RefundStatus
const (
	REFUNDSTATUS_PENDING RefundStatus = "PENDING"
	REFUNDSTATUS_ACCEPTED RefundStatus = "ACCEPTED"
	REFUNDSTATUS_REFUSED RefundStatus = "REFUSED"
)
