/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type ExpenseLogDto struct {

	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	ModifiedAt time.Time `json:"modifiedAt"`

	Author string `json:"author"`

	Field string `json:"field"`

	OldValue string `json:"oldValue,omitempty"`

	NewValue string `json:"newValue,omitempty"`

	Role UserRole `json:"role"`

	Action ExpenseLogAction `json:"action"`

	ExpenseId string `json:"expenseId"`
}
