/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type UserRole string

// List of UserRole
const (
	USERROLE_ADMIN UserRole = "ADMIN"
	USERROLE_OPERATOR UserRole = "OPERATOR"
	USERROLE_REVIEWER UserRole = "REVIEWER"
	USERROLE_EMPLOYEE UserRole = "EMPLOYEE"
)
