/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

type CreateExpenseDto struct {

	Categorization ExpenseCategory `json:"categorization"`

	// The ID of the allocated program
	ProgramId string `json:"programId"`

	// The date of the expense
	ExpenseAt time.Time `json:"expenseAt"`

	// The total amount
	TotalAmount float32 `json:"totalAmount"`
}
