/*
 * Protected API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ExpenseLogAction string

// List of ExpenseLogAction
const (
	EXPENSELOGACTION_EDIT_EXPENSE ExpenseLogAction = "EDIT_EXPENSE"
)
