/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Protected API
 * OpenAPI spec version: v1
 */

export type RefundStatus = typeof RefundStatus[keyof typeof RefundStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefundStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REFUSED: 'REFUSED',
} as const;
