name: Production deployment

on:
  push:
    tags:
      - prod_v*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -f build/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/...
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/...
